title: Ali Tamjid Ahmed Ajuad
logo: assets/image/IMG_20231106_104902_952 (2) (1).webp
description: Computer Science and Engineering student at Leading University, Sylhet, with a strong interest in software development, programming, and research. Skilled in C, C++, Java, SQL, and MySQL with knowledge of computer networks and database systems. Passionate about problem solving, learning new technologies, and collaborating on innovative projects. Actively involved in coding competitions, tech events, and research activities to continuously improve technical and professional skills.
show_downloads: true
theme: jekyll-theme-minimal
